This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./script.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file script.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (14 comparisons).
Generating output file script.acr....done (16 lines written, 0 warnings).
Output written in script.acr.
Transcript written in script.alg.
